
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab1_spart(

 //////////// CLOCK //////////
    input               CLOCK_50,
    input               CLOCK2_50,
    input               CLOCK3_50,
    input               CLOCK4_50,

 //////////// SEG7 //////////
    output      [6:0]  HEX0,
    output      [6:0]  HEX1,
    output      [6:0]  HEX2,
    output      [6:0]  HEX3,
    output      [6:0]  HEX4,
    output      [6:0]  HEX5,

//////////// KEY //////////
    input        [3:0]  KEY,

 //////////// LED //////////
    output		   [9:0]		LEDR,

 //////////// SW //////////
    input        [9:0]  SW,

 //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
    inout       [35:0]  GPIO
);

wire rxd;
wire [1:0] br_cfg;

// press button[0] to generate a low active reset signal
wire rst = ~KEY[0];

// GPIO[5] as RX input
assign rxd = GPIO[5];

// MIDI Signals
wire note_on_trigger;
wire [6:0] note_number;
wire [6:0] velocity;

// Instantiate midi receiver here
midi_receiver midi_receiver0(
    .clk(CLOCK_50),
    .rst_n(rst),
    .midi_rx(rxd),
    .note_on_trigger(note_on_trigger),
    .note_number(note_number),
    .velocity(velocity)
);

// Frequency LUT and Display Logic
wire [23:0] frequency_x1000;
wire [31:0] bcd_freq;

// LUT to get frequency * 1000 from note number
midi_freq_lut lut0 (
    .note(note_number),
    .frequency_x1000(frequency_x1000)
);

// Convert binary frequency to BCD for display
bin_to_bcd bcd0 (
    .bin(frequency_x1000),
    .bcd(bcd_freq)
);

reg [23:0] display_bcd;
always @(*) begin
    if (SW[0]) begin
        // Show upper digits (digits 2-7) for high frequencies
        display_bcd = bcd_freq[31:8]; 
    end else begin
        // Show lower digits (digits 0-5) normally
        display_bcd = bcd_freq[23:0];
    end
end

// Display the selected digits on HEX displays
seven_seg_decoder hex0_inst (.bin(display_bcd[3:0]),   .seg(HEX0));
seven_seg_decoder hex1_inst (.bin(display_bcd[7:4]),   .seg(HEX1));
seven_seg_decoder hex2_inst (.bin(display_bcd[11:8]),   .seg(HEX2));
seven_seg_decoder hex3_inst (.bin(display_bcd[15:12]),  .seg(HEX3));
seven_seg_decoder hex4_inst (.bin(display_bcd[19:16]),  .seg(HEX4));
seven_seg_decoder hex5_inst (.bin(display_bcd[23:20]),  .seg(HEX5));

endmodule
